Better, I think.

diff --git a/bin/lib/arg-processor b/bin/lib/arg-processor
--- a/bin/lib/arg-processor
+++ b/bin/lib/arg-processor
@@ -52,7 +52,7 @@ function opt-action {
     local name="$1"
 
     if ! [[ ${name} =~ ^([a-zA-Z0-9][-a-zA-Z0-9]*)(/[a-zA-Z0-9])?$ ]]; then
-        echo 1>&2 "Invalid action-option name: ${name}"
+        echo 1>&2 "Invalid option name: ${name}"
         return 1
     fi
 
@@ -127,7 +127,7 @@ function opt-toggle {
     local name="$1"
 
     if ! [[ ${name} =~ ^([a-zA-Z0-9][-a-zA-Z0-9]*)(/[a-zA-Z0-9]?)?(/[a-zA-Z0-9])?$ ]]; then
-        echo 1>&2 "Invalid toggle-option name: ${name}"
+        echo 1>&2 "Invalid option name: ${name}"
         return 1
     fi
 
@@ -230,7 +230,7 @@ function opt-value {
     local name="$1"
 
     if ! [[ ${name} =~ ^[a-zA-Z0-9][-a-zA-Z0-9]*$ ]]; then
-        echo 1>&2 "Invalid value-option name: ${name}"
+        echo 1>&2 "Invalid option name: ${name}"
         return 1
     fi
 
