Pull out parsing into a separate function. (See explanation.)

diff --git a/bin/lib/arg-processor b/bin/lib/arg-processor
--- a/bin/lib/arg-processor
+++ b/bin/lib/arg-processor
@@ -30,81 +30,18 @@ function process-args {
         eval "${_argproc_d}"
     done
 
-    # Main processing loop.
-
+    # Build up the statements to evaluate.
     local _argproc_statements=()
-    local argError=0
-    local arg handler name value
+    _argproc:statements-from-args "$@"
 
-    while (( $# > 0 )); do
-        arg="$1"
-
-        if [[ ${arg} == '--' ]]; then
-            # Explicit end of options.
-            shift
-            break
-        elif [[ ${arg} == '-' || ${arg} =~ ^[^-] ]]; then
-            # Non-option argument.
-            break
-        elif [[ ${arg} =~ ^--([-a-zA-Z0-9]+)(=.*)?$ ]]; then
-            # Long-form argument.
-            name="${BASH_REMATCH[1]}"
-            value="${BASH_REMATCH[2]}"
-            handler="_argproc:long-${name}"
-            if ! declare -F "${handler}" >/dev/null; then
-                echo 1>&2 "Unknown option: --${name}"
-                argError=1
-            elif [[ ${value} == '' ]]; then
-                _argproc_statements+=("${handler}")
-            else
-                # `:1` to drop the `=` from the start of `value`
-                _argproc_statements+=("${handler} $(_argproc:quote "${value:1}")")
-            fi
-        elif [[ $arg =~ ^-([a-zA-Z0-9]+)$ ]]; then
-            # Short-form argument.
-            arg="${BASH_REMATCH[1]}"
-            while [[ ${arg} =~ ^(.)(.*)$ ]]; do
-                name="${BASH_REMATCH[1]}"
-                arg="${BASH_REMATCH[2]}"
-                handler="_argproc:shortcut-${name}"
-                if ! declare -F "${handler}" >/dev/null; then
-                    echo 1>&2 "Unknown option: -${name}"
-                    argError=1
-                    # Break, to avoid spewing a ton of errors in case of a
-                    # pilot error along the lines of `-longOptionName`.
-                    break
-                else
-                    _argproc_statements+=("${handler}")
-                fi
-            done
-        else
-            # Something weird and invalid, e.g. `--=`.
-            echo 1>&2 "Invalid option: ${arg}"
-            argError=1
-        fi
-
-        shift
-    done
-
-    if declare -F _argproc:rest >/dev/null; then
-        _argproc_statements+=('_argproc:rest "$@"')
-    elif (( $# > 0 )); then
-        echo 1>&2 'Non-option arguments are not allowed.'
-        argError=1
-    fi
-
-    if (( argError != 0 )); then
-        return "${argError}"
-    fi
-
-    # Evaluate all the handler call statements.
-
+    # Evaluate them!
+    local _argproc_error=0
     local _argproc_s
     for _argproc_s in "${_argproc_statements[@]}"; do
-        eval "${_argproc_s}" || argError="$?"
+        eval "${_argproc_s}" || _argproc_error="$?"
     done
 
-    return "${argError}"
+    return "${_argproc_error}"
 }
 
 # Declares an "action" option. If a slash and single character are appended to
@@ -413,9 +350,96 @@ function rest-arg {
 # Library-internal functions
 #
 
-# Quotes a literal string, so it can be safely used in evaluated code.
+# Builds up a list of statements to evaluate, based on the given arguments. It
+# is stored in the variable `_argproc_statements`, which is assumed to be
+# declared by its caller.
+#
+# Note: This arrangement, where argument parsing is done in a separate
+# function and as a separate pass from evaluation, makes it possible to use
+# non-mangled local variables in the more tricky code, so it's a bit nicer to
+# read.
+function _argproc:statements-from-args {
+    local argError=0
+    local arg handler name value
+
+    while (( $# > 0 )); do
+        arg="$1"
+
+        if [[ ${arg} == '--' ]]; then
+            # Explicit end of options.
+            shift
+            break
+        elif [[ ${arg} == '-' || ${arg} =~ ^[^-] ]]; then
+            # Non-option argument.
+            break
+        elif [[ ${arg} =~ ^--([-a-zA-Z0-9]+)(=.*)?$ ]]; then
+            # Long-form argument.
+            name="${BASH_REMATCH[1]}"
+            value="${BASH_REMATCH[2]}"
+            handler="_argproc:long-${name}"
+            if ! declare -F "${handler}" >/dev/null; then
+                echo 1>&2 "Unknown option: --${name}"
+                argError=1
+            elif [[ ${value} == '' ]]; then
+                _argproc_statements+=("${handler}")
+            else
+                # `:1` to drop the `=` from the start of `value`
+                _argproc_statements+=("${handler} $(_argproc:quote "${value:1}")")
+            fi
+        elif [[ $arg =~ ^-([a-zA-Z0-9]+)$ ]]; then
+            # Short-form argument.
+            arg="${BASH_REMATCH[1]}"
+            while [[ ${arg} =~ ^(.)(.*)$ ]]; do
+                name="${BASH_REMATCH[1]}"
+                arg="${BASH_REMATCH[2]}"
+                handler="_argproc:shortcut-${name}"
+                if ! declare -F "${handler}" >/dev/null; then
+                    echo 1>&2 "Unknown option: -${name}"
+                    argError=1
+                    # Break, to avoid spewing a ton of errors in case of a pilot
+                    # error along the lines of `-longOptionName`.
+                    break
+                else
+                    _argproc_statements+=("${handler}")
+                fi
+            done
+        else
+            # Something weird and invalid, e.g. `--=`.
+            echo 1>&2 "Invalid option: ${arg}"
+            argError=1
+        fi
+
+        shift
+    done
+
+    if declare -F _argproc:rest >/dev/null; then
+        local statement="_argproc:rest $(_argproc:quote "$@")"
+        _argproc_statements+=("${statement}")
+    elif (( $# > 0 )); then
+        echo 1>&2 'Non-option arguments are not allowed.'
+        argError=1
+    fi
+
+    return "${argError}"
+}
+
+# Quotes one or more literal strings, space separated, so they can be safely
+# used in evaluated code. This (successfully) prints nothing if no arguments are
+# given.
 function _argproc:quote {
-    printf '%q' "$1"
+    case "$#" in
+        0)
+            : # Nothing to print.
+            ;;
+        1)
+            printf '%q' "$1"
+            ;;
+        *)
+            printf '%q' "$1"
+            shift
+            printf ' %q' "$@"
+            ;;
+    esac
 }
 
 
