Use `arg-processor`.

diff --git a/bin/lib/json-length b/bin/lib/json-length
--- a/bin/lib/json-length
+++ b/bin/lib/json-length
@@ -31,47 +31,29 @@ function usage {
     exit "$1"
 }
 
-# Error during argument processing?
-argError=0
+# Want help?
+opt-action --call=usage --value=0 help/h
 
 # JSON value.
+rest-arg --call=parse-rest
 value=''
-
-while (( $# > 0 )); do
-    case "$1" in
-        -h|--help)
-            argError=-1 # `-1` suppresses error exit after displaying usage.
-            break
+function parse-rest {
+    case "$#" in
+        0)
+            echo 1>&2 'Missing JSON value argument.'
+            return 1
             ;;
-        --)
-            # Explicit end of options.
-            shift
-            break
-            ;;
-        -?*)
-            echo 1>&2 "Unknown option: $1"
-            argError=1
-            break
+        1)
+            value="$1"
             ;;
         *)
-            # Non-option argument.
-            break
+            echo 1>&2 'Extra arguments.'
+            return 1
             ;;
     esac
+}
 
-    shift
-done
-
-if (( $# > 0 )); then
-    value="$1"
-else
-    echo 1>&2 'Missing JSON value argument.'
-    argError=1
-fi
-
-if (( argError )); then
-    usage "${argError}"
-fi
+process-args "$@" || usage "$?"
 
 
 #
