Rename for clarity.

diff --git a/arg-processor/arg-processor b/arg-processor/arg-processor
--- a/arg-processor/arg-processor
+++ b/arg-processor/arg-processor
@@ -110,7 +110,7 @@ function opt-choice {
     local optRequired=0
     local optVar=''
     local args=("$@")
-    _argproc_janky-args --multi-spec call default required var \
+    _argproc_janky-args --multi-arg call default required var \
     || return 1
 
     if [[ ${optVar} != '' ]]; then
@@ -155,7 +155,7 @@ function opt-enum {
     local optRequired=0
     local optVar=''
     local args=("$@")
-    _argproc_janky-args --multi-spec call default required var \
+    _argproc_janky-args --multi-arg call default required var \
     || return 1
 
     local specName=''
@@ -384,7 +384,7 @@ function process-args {
 # Requires that exactly one of the indicated arguments / options is present.
 function require-exactly-one-arg-of {
     local args=("$@")
-    _argproc_janky-args --multi-spec \
+    _argproc_janky-args --multi-arg \
     || return 1
 
     local allNames=()
@@ -642,12 +642,12 @@ function _argproc_define-value-required-arg {
 # parsed option. Assumes the variable `args` (again presumed local to the
 # caller) contains all the arguments, which gets updates by this function.
 # After option parsing, this expects there to be one argument remaining, except
-# if `--multi-spec` is passed to this function, in which case there must be at
+# if `--multi-arg` is passed to this function, in which case there must be at
 # least one.
 function _argproc_janky-args {
-    multiSpec=0
-    if [[ $1 == '--multi-spec' ]]; then
-        multiSpec=1
+    multiArg=0
+    if [[ $1 == '--multi-arg' ]]; then
+        multiArg=1
         shift
     fi
 
@@ -739,10 +739,10 @@ function _argproc_janky-args {
    fi
 
    if (( ${#args[@]} == 0 )); then
-       echo 1>&2 'Missing specification.'
+       echo 1>&2 'Missing argument specification.'
        return 1
-   elif (( ${#args[@]} > 1 && !multiSpec )); then
-       echo 1>&2 'Too many specifications.'
+   elif (( ${#args[@]} > 1 && !multiArg )); then
+       echo 1>&2 'Too many arguments.'
        return 1
    fi
 }
