Factor out common code for generating handler functions.

diff --git a/arg-processor/arg-processor b/arg-processor/arg-processor
--- a/arg-processor/arg-processor
+++ b/arg-processor/arg-processor
@@ -420,23 +420,17 @@ function rest-arg {
     _argproc_parse-spec "${args[0]}" \
     || return 1
 
-    if [[ ${optCall} != '' ]]; then
-        # Re-form as the caller code.
-        optCall="${optCall}"' "$@" || return "$?"'
+    if [[ ${optVar} != '' ]]; then
+        # Set up the default initializer.
+        _argproc_initStatements+=("${optVar}=()")
     fi
 
-    if [[ ${optVar} != '' ]]; then
-        # Set up the default initializer, and then re-form as the setter code.
-        _argproc_initStatements+=("${optVar}=()")
-        optVar="${optVar}"'=("$@")'
-    fi
+    local handlerBody="$(
+        _argproc_handler-body "${specName}" '' "${optCall}" "${optVar}"
+    )"
 
     eval 'function _argproc:rest {
-        '"${optCall}"'
-        '"${optVar}"'
-        if (( $# > 0 )); then
-            _argproc_receivedArgNames+="<'"${specName}"'>"
-        fi
+        '"${handlerBody}"'
     }'
 }
 
@@ -552,30 +546,22 @@ function _argproc_define-no-value-arg {
     local abbrevChar="$4"
     local value="$5"
 
+    _argproc_set-arg-description "${longName}" option || return 1
+
+    local handlerName="_argproc:long-${longName}"
+    local handlerBody="$(
+        _argproc_handler-body "${longName}" '' "${callFunc}" "${varName}"
+    )"
+
     value="$(_argproc_quote "${value}")"
 
-    _argproc_set-arg-description "${longName}" option \
-    || return 1
-
-    if [[ ${callFunc} != '' ]]; then
-        # Re-form as the caller code.
-        callFunc="${callFunc} ${value}"' || return "$?"'
-    fi
-
-    if [[ ${varName} != '' ]]; then
-        # Re-form as the setter code.
-        varName="${varName}=${value}"
-    fi
-
-    eval 'function _argproc:long-'"${longName}"' {
+    eval 'function '"${handlerName}"' {
         if (( $# > 0 )); then
             echo 1>&2 "Value not allowed for option --'"${longName}"'."
             return 1
         fi
-
-        '"${callFunc}"'
-        '"${varName}"'
-        _argproc_receivedArgNames+="<'"${longName}"'>"
+        set '"${value}"'
+        '"${handlerBody}"'
     }'
 
     if [[ ${abbrevChar} != '' ]]; then
@@ -607,52 +593,80 @@ function _argproc_define-value-required-arg {
         handlerName="_argproc:positional-${longName}"
     fi
 
-    if [[ ${callFunc} != '' ]]; then
-        # Re-form as the caller code.
-        callFunc="${callFunc}"' "$1" || return "$?"'
-    fi
-
-    if [[ ${varName} != '' ]]; then
-        # Re-form as the setter code.
-        varName="${varName}"'="$1"'
-    fi
-
-    if [[ ${filter} =~ ^/(.*)/$ ]]; then
-        # Re-form `filter` as the statement which performs the regex check.
-        filter="${BASH_REMATCH[1]}"
-        filter='
-            if ! [[ $1 =~ '"${filter}"' ]]; then
-                echo 1>&2 "Invalid value for '"${desc}"': ${_argproc_value}"
-                return 1
-            fi'
-    elif [[ ${filter} =~ ^\{(.*)\}$ ]]; then
-        # Re-form `filter` as the code block to run.
-        filter="$(printf '{\n%s\n} || return "$?"\n' "${BASH_REMATCH[1]}")"
-    elif [[ ${filter} != '' ]]; then
-        # Re-form `filter` as the call to the filter function. Note: We can't
-        # do `set "$(...)"` or assign on the `local` line, because either of
-        # those will swallow a failure from the call.
-        filter="$(printf '
-            local _argproc_value
-            _argproc_value="$(%s "$1")" || return 1
-            set "${_argproc_value}"
-            ' "${filter}")"
-    fi
+    local handlerBody="$(
+        _argproc_handler-body "${longName}" "${filter}" "${callFunc}" "${varName}"
+    )"
 
     eval 'function '"${handlerName}"' {
         if (( $# < 1 )); then
             echo 1>&2 "Value required for '"${desc}"'."
             return 1
         fi
-        '"${filter}"'
-        '"${callFunc}"'
-        '"${varName}"'
-        _argproc_receivedArgNames+="<'"${longName}"'>"
+        '"${handlerBody}"'
     }'
 
     if [[ ${abbrevChar} != '' ]]; then
         _argproc_define-abbrev "${abbrevChar}" "${longName}"
     fi
+}
+
+# Produce an argument handler body, from the given components.
+function _argproc_handler-body {
+    local longName="$1"
+    local filter="$2"
+    local callFunc="$3"
+    local varName="$4"
+    local result=()
+
+    if [[ ${filter} =~ ^/(.*)/$ ]]; then
+        # Add a loop to perform the regex check on each argument.
+        filter="${BASH_REMATCH[1]}"
+        result+=(
+            "$(printf '
+                local _argproc_value
+                for _argproc_value in "$@"; do
+                    if ! [[ $1 =~ %s ]]; then
+                        echo 1>&2 "Invalid value for %s: ${_argproc_value}"
+                        return 1
+                    fi
+                done' \
+                "${filter}" "${desc}")"
+        )
+    elif [[ ${filter} =~ ^\{(.*)\}$ ]]; then
+        # Add a compound statement for the code block.
+        result+=(
+            "$(printf '{\n%s\n} || return "$?"\n' "${BASH_REMATCH[1]}")"
+        )
+    elif [[ ${filter} != '' ]]; then
+        # Add a loop to call the filter function on each argument.
+        result+=(
+            "$(printf '
+                local _argproc_value _argproc_args=()
+                for _argproc_value in "$@"; do
+                    _argproc_args+=("$(%s "${_argproc_value}")") || return 1
+                done
+                set "${_argproc_args[@]}"' \
+                "${filter}")"
+        )
+    fi
+
+    if [[ ${callFunc} != '' ]]; then
+        result+=(
+            "$(printf '%s "$@" || return "$?"' "${callFunc}")"
+        )
+    fi
+
+    if [[ ${varName} != '' ]]; then
+        result+=(
+            "$(printf '%s=("$@")' "${varName}")"
+        )
+    fi
+
+    result+=(
+        "$(printf '_argproc_receivedArgNames+="<%s>"' "${longName}")"
+    )
+
+    printf '%s\n' "${result[@]}"
 }
 
 # Janky yet reasonable argument parser for the commands in this library. (How
@@ -665,7 +679,7 @@ function _argproc_define-value-required-arg {
 # if `--multi-arg` is passed to this function, in which case there must be at
 # least one.
 function _argproc_janky-args {
-    multiArg=0
+    local multiArg=0
     if [[ $1 == '--multi-arg' ]]; then
         multiArg=1
         shift
